### PR TITLE
#400 correcting docblock type for generated "valueHolder" properties

### LINKED ISSUE #400: `LazyLoadingValueHolder` generated properties incorrectly documented
Generated `LazyLoadingValueHolder` proxies have an incorrectly documented `valueHolder` property.

### PR DESCRIPTION
**Pull request by Ocramius**
Property is now correctly mapped as `OriginalType|null`

Fixes #400

### CODE REVIEW

File: src/ProxyManager/ProxyGenerator/AccessInterceptorValueHolderGenerator.php [hunk 1]
```diff
@@ -64,7 +64,7 @@ public function generate(ReflectionClass $originalClass, ClassGenerator $classGe
         }
 
         $classGenerator->setImplementedInterfaces($interfaces);
-        $classGenerator->addPropertyFromGenerator($valueHolder        = new ValueHolderProperty());
+        $classGenerator->addPropertyFromGenerator($valueHolder        = new ValueHolderProperty($originalClass));
```
Comment (malukenho) [inline src/ProxyManager/ProxyGenerator/AccessInterceptorValueHolderGenerator.php]: `ValueHolderProperty#__construct()` doesn't accept parameters 👀
