### PR TITLE
Revert BC break - `: void` cannot be added as return type to open classes

### LINKED ISSUE #451: synfony integration
I have an issue with proxymanager since this week end

PHP Fatal error:  Declaration of Symfony\\Bridge\\ProxyManager\\LazyProxy\\PhpDumper\\LazyLoadingValueHolderGenerator::generate(ReflectionClass $originalClass, Zend\\Code\\Generator\\ClassGenerator $classGenerator) must be compatible with ProxyManager\\ProxyGenerator\\LazyLoadingValueHolderGenerator::generate(ReflectionClass $originalClass, Zend\\Code\\Generator\\ClassGenerator $classGenerator): void in /var/www/xxxxxxxxxx/release-1.4.2-20190319084524/vendor/symfony/symfony/src/Symfony/Bridge/ProxyManager/LazyProxy/PhpDumper/LazyLoadingValueHolderGenerator.php on line 20

can you please check this issue thanks

### PR DESCRIPTION
**Pull request by Ocramius**
Fixes #451 
Reverts the BC break of ` : void` being added to open classes in a minor release.

### CODE REVIEW

File: src/ProxyManager/Signature/SignatureChecker.php [hunk 1]
```diff
@@ -42,6 +42,6 @@ public function checkSignature(ReflectionClass $class, array $parameters) : void
                 $defaultProperties[$propertyName],
                 $signature
             );
-        }
+        } : void
```
Comment (Ocramius) [inline src/ProxyManager/Signature/SignatureChecker.php]: Maybe if I didn't add random syntax errors to my stuff -.-''
